name: cred_app
description: A new Flutter project.



version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_launcher_icons: ^0.13.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  intl: ^0.19.0
  flutter_bloc: ^8.1.6
  http: ^1.2.2
  equatable: ^2.0.5
  syncfusion_flutter_gauges: ^27.1.53
  syncfusion_flutter_core: ^27.1.53
  syncfusion_flutter_sliders: ^27.1.53




flutter:
  fonts:
    - family: Figtree-Regular
      fonts:
        - asset: lib/assets/fonts/Figtree-Regular.ttf

  uses-material-design: true
  assets:
    - lib/assets/
    - lib/assets/icons/
    - lib/assets/images/
